name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - name: Install XCOV
        run: sudo gem install xcov
      - name: Create code coverage report
        run: |
          xcov -p ../cardview2.xcodeproj -s cardview2 -o xcov_output