name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Build & Tests
        run: xcodebuild -project cardview2.xcodeproj/ -scheme cardview2 -derivedDataPath Build/ -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Install XCOV
        run: sudo gem install xcov
      - name: Create code coverage report
        run: xcov -p cardview2.xcodeproj -s cardview2 -o xcov_output